version: '3.3'
services:
  node:
    build:
      context: ./Back/Nodejs
    # profile: ["node"]
    volumes:
      - ./Back/Nodejs:/src
    command: sh -c "npm i && npm run dev"
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*

  react:
    image: node:14-alpine
    # profile: ["react"]
    volumes:
      - ./Front/React:/app
    command: sh -c "cd /app && npm i && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: post_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  
  # mongo:
    # image: mongo:latest
