version: '3.3'
services:

  # react:
  #   image: node:14-alpine
  #   # profile: ["react"]
  #   volumes:
  #     - ./Front/React:/app
  #   command: sh -c "cd /app && npm i && npm start"
  #   ports:
  #     - "3000:3000"

##############################################################
########################[NODE BACKEND]########################
##############################################################

  # node:
  #   build:
  #     context: ./Back/Nodejs
  #   # profile: ["node"]
  #   volumes:
  #     - ./Back/Nodejs:/src
  #   command: sh -c "npm i && npm run dev"
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     NODE_ENV: development
  #     DEBUG: nodejs-docker-express:*
  #   depends_on:
  #     - postgres_db

  # postgres_db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: post_db
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin

##############################################################
#######################[PYTHON BACKEND]#######################
##############################################################

  django:
    build: 
      context: ./Back/Python
    volumes:
      - ./Back/Python:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
  
  mongo_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'
