version: '3.8'
services:
  node:
    build:
      context: ./Back/Nodejs
    volumes:
      - ./Back/Nodejs:/src
    command: sh -c "npm i && npm run dev"
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*

  react:
    image: node:14-alpine
    volumes:
      - ./Front/React:/app
    command: sh -c "cd /app && npm i && npm start"
    ports:
      - "3000:3000"
